#!/usr/bin/env bash

XPLA_DIMENSION_HOME=/data/lib/xplad/dimension_37-1

xplad_v1.2.0 init --chain-id dimension_37-1 --home=${XPLA_DIMENSION_HOME} xpla-dimension-0 && \
    wget -O ${XPLA_DIMENSION_HOME}/config/genesis.json https://raw.githubusercontent.com/xpladev/mainnet/main/dimension_37-1/genesis.json && \
    sed -i -e 's/minimum-gas-prices = \"\"/minimum-gas-prices = \"850000000000axpla\"/g' ${XPLA_DIMENSION_HOME}/config/app.toml && \
    sed -i -e 's/pruning = \"default\"/pruning = \"nothing\"/g' ${XPLA_DIMENSION_HOME}/config/app.toml && \
    sed -i -e '/\[api\]/,+3 s/enable = false/enable = true/g' ${XPLA_DIMENSION_HOME}/config/app.toml && \
    sed -i -e '/\[api\]/,+6 s/swagger = false/swagger = true/g' ${XPLA_DIMENSION_HOME}/config/app.toml && \
    sed -i -e 's/seeds = \"\"/seeds = \"e7b6016ce5663a69ba71a982072315545eb0d5f6@seed.xpla.delightlabs.io:26656\"/g' ${XPLA_DIMENSION_HOME}/config/config.toml && \
    sed -i -e 's/max_packet_msg_payload_size = 1024/max_packet_msg_payload_size = 4096/g' ${XPLA_DIMENSION_HOME}/config/config.toml
