#!/usr/bin/env bash

xplad_v1.0.0 init --chain-id dimension_37-1 xpla-node-0 && \
    wget -O ~/.xpla/config/genesis.json https://raw.githubusercontent.com/xpladev/mainnet/main/dimension_37-1/genesis.json && \
    sed -i -e 's/minimum-gas-prices = \"\"/minimum-gas-prices = \"850000000000axpla\"/g' ~/.xpla/config/app.toml && \
    sed -i -e 's/pruning = \"default\"/pruning = \"nothing\"/g' ~/.xpla/config/app.toml && \
    sed -i -e '/\[api\]/,+3 s/enable = false/enable = true/g' ~/.xpla/config/app.toml && \
    sed -i -e '/\[api\]/,+6 s/swagger = false/swagger = true/g' ~/.xpla/config/app.toml && \
    sed -i -e 's/seeds = \"\"/seeds = \"e7b6016ce5663a69ba71a982072315545eb0d5f6@seed.xpla.delightlabs.io:26656\"/g' ~/.xpla/config/config.toml && \
    sed -i -e 's/max_packet_msg_payload_size = 1024/max_packet_msg_payload_size = 4096/g' ~/.xpla/config/config.toml
